using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
internal sealed partial class ChatCompletion : Popup
{
    private static readonly ISawmill Sawmill = Logger.GetSawmill("chat");
    public ChatCompletion()
    {
        RobustXamlLoader.Load(this);
        OnPopupOpen += HandlePopupOpen;
        OnPopupHide += HandlePopupHide;
    }
    private void HandlePopupOpen()
    {
        Sawmill.Info("ChatCompletion popup opened");
    }

    private void HandlePopupHide()
    {
        Sawmill.Info("ChatCompletion popup closed");
    }
}